### PR TITLE
docs: LICENSE

### PR DESCRIPTION
**Pull request by EA-pbu**
added MIT License file

### CODE REVIEW

**Comment by zposten** [comment]
Hey @EA-pbu, thanks for the PR!

My intention is definitely for this package to be fully open source. The [package.json's license field](https://github.com/zposten/gremlin-cosmos/blob/43b088c5d6e27588196685840e52bc0121ab9438/package.json#L8) has a value of `"MIT"`.  Is there a reason that that along does not suffice to specify the license?

**Comment by EA-pbu** [comment]
Hi @zposten !
Appreciate your swift response, thanks a lot.

Indeed you have mentioned MIT license in package.json . By no means I claim to have a deep knowledge of all legal peculiarities of open-source projects.
I'm only coming from suggestion that sometimes people would like to see actual license file that includes the details for legal use of your code. And mentioning "MIT" in package.json is not really informative in such case.
And other reason that I think it may be useful to include a LICENSE file is just because all popular npm packages are having 
actual LICENSE files in their repositories. Big corporations are behind these packages and I think they have a reason including an actual LICENSE file to their repositories on top of mentioning it swiftly in packages.json

You can have a look:
https://github.com/expressjs/express
https://github.com/facebook/jest
https://github.com/Microsoft/TypeScript

**Comment by zposten** [comment]
@EA-pbu Good points all!  Thanks for discussing it with me.  I agree we should add the LICENSE file.

Could you possibly add my email to the copyright line please?  Then I'll merge this in publish a new version

```
Copyright (c) 2021 Zach Posten <zach@posten.io>
```

**Comment by EA-pbu** [comment]
sure! included your email

**Comment by zposten** [comment]
Thank you!

**Comment by 0livare** [comment]
@EA-pbu Just a heads up v0.0.14 is out with all these changes.  Thanks so much for you contributions!

**Pull request merged**
